title: <p align="center"> "Ho Viet Hoang" </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/viet-hoang-ho-5ba443152/">LinkedIn</a> |
  <a href="https://github.com/hoangho0908">GitHub</a>
  </p>
  
  <p align="justify">
  While living and studying in the United Kingdom, I graduated from University of Sussex with a BSc Degree in Business and Finance, followed by MSc Degree in Business Analytics
  <br><br>
  Currently, I am looking for the opportunity to get hands-on exposure and apply my expertise in Business Administration and Data Analysis in a professional environment.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
