title: <p align="center"> Hồ Việt Hoàng </p>

logo: "/images/pictures.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/viet-hoang-ho-5ba443152/">LinkedIn</a> |
  <a href="https://github.com/hoangho0908">GitHub</a>
  </p>
  
  <p align="justify">
  Trong quá trình học tập và sinh sống tại Anh Quốc, tôi đã tốt nghiệp bằng Cử nhân chuyên ngành Tài chính & Quản trị Kinh doanh (Business and Finance) và bằng Thạc sĩ chuyên ngành Phân tích Kinh Doanh (Business Analytics)
  <br><br>
  Hiện tại, tôi đang tìm kiếm cơ hội tiếp xúc thực tế và áp dụng kiến thức chuyên môn về quản trị kinh doanh và phân tích dữ liệu trong một môi trường chuyên nghiệp. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
